### ISSUE TITLE
where are SubFasta and SizeFasta

### ISSUE THREAD

**Issue by aic123** [skoren/PilonGrid#1]
Hi.koren
 I'm using PilonGrid. But I got some trouble.  
In the script "pilonParallelSGE.sh",there is 
"java -Xmx60g SubFasta $utg.$jobid.cut $ASM > $utg.$jobid.fasta "   
and   in the script "pilon.sh" :
"java SizeFasta $ASM > $LEN"    

But I can not find where are "SizeFasta" and "SubFasta"  in the path of PilonGrid ,can you tell me  how can I  find them ?
Thanks!

**Comment by skoren** [comment]
Those are my utilities that were missing from the repo, I've added them now.

**Comment by aic123** [comment]
OK，I got it.
Thanks very much for your help.

aic
